In [6]:
import tensorflow as tf
mat0 = tf.constant([[0,0,0],[0,0,0]])
mat1 = tf.zeros([2,3]) #全零矩阵
mat2 = tf.ones([3,2]) #全1矩阵
mat3 = tf.fill([2,3],15) #填充矩阵
with tf.Session() as sess:
    print(sess.run(mat0))
    print(sess.run(mat1))
    print(sess.run(mat2))
    print(sess.run(mat3))

[[0 0 0]
 [0 0 0]]
[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1.]
 [1. 1.]
 [1. 1.]]
[[15 15 15]
 [15 15 15]]


In [11]:
import tensorflow as tf
mat1 = tf.constant([[2],[3],[4]])
mat2 = tf.zeros_like(mat1) #mat2维度等于mat1维度
mat3 = tf.linspace(0.0,2.0,11) #将0到2分成十等份
mat4 = tf.random_uniform([2,3],-1,2) #产生从-1到2的随机矩阵
with tf.Session() as sess:
    print(sess.run(mat2))
    print(sess.run(mat3))
    print(sess.run(mat4))

[[0]
 [0]
 [0]]
[0.        0.2       0.4       0.6       0.8       1.        1.2
 1.4       1.6       1.8000001 2.       ]
[[-0.05263484  0.49153244 -0.22489774]
 [-0.12712479  1.5091507   1.7580514 ]]
