In [ ]:
'''
Learning notes for "Learning Computer Vision"
Created by Xiaoxiao
2019.8.30
'''
import cv2
import numpy as np
newImgInfo = (500,500,3)
dst = np.zeros(newImgInfo,np.uint8)

cv2.rectangle(dst,(50,100),(200,300),(255,0,0),-1)
# 1 dst 2 start 3 end 4 color 5 fill -1:填充 >0:线条宽度
cv2.circle(dst,(250,250),(50),(0,255,0),2)
# 2 center 3 r 4 color 5 fill
cv2.ellipse(dst,(256,256),(150,100),0,0,180,(250,250,0),-1)
# 2 center 3 轴(长轴，短轴) 4 偏转角度 5 begin angle 6 end angle 7 fill

points = np.array([[150,50],[140,140],[200,170],[250,250],[150,50]],np.int32)
# 顶点个数为5
points = points.reshape((-1,1,2))
# 转置成5*1*2维矩阵
print(points)
print(points.shape)
cv2.polylines(dst,[points],True,(0,255,255))
# 2 points 3 bool 是否封闭 4 color
cv2.imshow('dst',dst)
cv2.waitKey(0)

[[[150  50]]

 [[140 140]]

 [[200 170]]

 [[250 250]]

 [[150  50]]]
(5, 1, 2)
